# Generated by Django 5.2.7 on 2025-10-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_farmer_gender_farmer_is_contracted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='is_contracted',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
